// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCodeFirstWithDB
{
    public partial class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Rate { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
    }
}