// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace winFormSqlFirst.Models
{
    public partial class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Rate { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
    }
}